### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by MigrantBirdd** [Jirgap/AutoSnapBot#1]
hey there
thanks for your good jobs;
i got an error in last cmmnd line as:

Traceback (most recent call last):
  File "C:\Users\IDK\AutoSnapBot\main.py", line 4, in <module>
    import keyboard
ModuleNotFoundError: No module named 'keyboard'

it's pleasure if you help and let me know who to fix it out
thanks

**Comment by d3v7** [comment]
> hey there
> 
> thanks for your good jobs;
> 
> i got an error in last cmmnd line as:
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "C:\Users\IDK\AutoSnapBot\main.py", line 4, in <module>
> 
>     import keyboard
> 
> ModuleNotFoundError: No module named 'keyboard'
> 
> 
> 
> it's pleasure if you help and let me know who to fix it out
> 
> thanks

Try this

```
pip install keyboard
```

**Comment by Jirgap** [comment]
Thank you for raising this with me, and i appricate [d3v7](https://github.com/d3v7) giving you the soultion.

I have updated the requirments file to add in this module to prevent this issue

**Comment by MigrantBirdd** [comment]
and another error after installed keyboard:

Traceback (most recent call last):
  File "C:\Users\IDK\AutoSnapBot\main.py", line 34, in <module>
    find_go_back_button = pyautogui.locateOnScreen(snapchat_back, grayscale=False, confidence=0.9)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IDK\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyautogui\__init__.py", line 175, in wrapper
    return wrappedFunction(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IDK\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyautogui\__init__.py", line 213, in locateOnScreen
    return pyscreeze.locateOnScreen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IDK\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyscreeze\__init__.py", line 373, in locateOnScreen
    retVal = locate(image, screenshotIm, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IDK\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyscreeze\__init__.py", line 353, in locate
    points = tuple(locateAll(needleImage, haystackImage, **kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\IDK\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyscreeze\__init__.py", line 253, in _locateAll_python
    raise NotImplementedError('The confidence keyword argument is only available if OpenCV is installed.')
NotImplementedError: The confidence keyword argument is only available if OpenCV is installed.

**Comment by MigrantBirdd** [comment]
bro whats going on you? you closed the issue without asked is that fine or not? pretty poor support and low knowledge as it appears. 
Also afte ur suggestion to install keyboard; we got other error but i dont interest at all to continue by this cheap support.

**Comment by d3v7** [comment]
> bro whats going on you? you closed the issue without asked is that fine or not? pretty poor support and low knowledge as it appears. 
> 
> Also afte ur suggestion to install keyboard; we got other error but i dont interest at all to continue by this cheap support.

Please mention the error you are getting.

**Comment by Jirgap** [comment]
> bro whats going on you? you closed the issue without asked is that fine or not? pretty poor support and low knowledge as it appears. Also afte ur suggestion to install keyboard; we got other error but i dont interest at all to continue by this cheap support.

dv37 answered your question, and i have updated the requirements text? Your issue was you were getting 

This error:
Traceback (most recent call last):
File "C:\Users\IDK\AutoSnapBot\main.py", line 4, in
import keyboard
ModuleNotFoundError: No module named 'keyboard

If you had a further issue you could open a new ticket or say it here, the soultion was given to you.

**Comment by Jirgap** [comment]
@MigrantBirdd The issue you are facing is that OpenCV is not installed on your machine, please run the following command to install it.

pip install opencv-python

**Comment by Jirgap** [comment]
User did not respond, closing ticket.
