### ISSUE TITLE
pyautogui

### ISSUE THREAD

**Issue by crossdefalt** [Jirgap/AutoSnapBot#2]
┌──(s1yn㉿sec)-[~/AutoSnapBot]
└─$ sudo   python main.py     
Traceback (most recent call last):
  File "/home/s1yn/AutoSnapBot/main.py", line 1, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
                                                                                                                                                                      
┌──(s1yn㉿sec)-[~/AutoSnapBot]
└─$ sudo   python2 main.py
  File "main.py", line 49
    print(f"{replies} New Snap Detected ")
                                        ^
SyntaxError: invalid syntax
                                                                                                                                                                      
┌──(s1yn㉿sec)-[~/AutoSnapBot]
└─$ sudo   python3 main.py
Traceback (most recent call last):
  File "/home/s1yn/AutoSnapBot/main.py", line 1, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'
                                                                                                                                                                      
┌──(s1yn㉿sec)-[~/AutoSnapBot]
└─$ pip install pyautogui 
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyautogui in /home/s1yn/.local/lib/python3.11/site-packages (0.9.53)
Requirement already satisfied: PyTweening>=1.0.1 in /home/s1yn/.local/lib/python3.11/site-packages (from pyautogui) (1.0.4)
Requirement already satisfied: mouseinfo in /home/s1yn/.local/lib/python3.11/site-packages (from pyautogui) (0.1.3)
Requirement already satisfied: pygetwindow>=0.0.5 in /home/s1yn/.local/lib/python3.11/site-packages (from pyautogui) (0.0.9)
Requirement already satisfied: pymsgbox in /home/s1yn/.local/lib/python3.11/site-packages (from pyautogui) (1.0.9)
Requirement already satisfied: pyscreeze>=0.1.21 in /home/s1yn/.local/lib/python3.11/site-packages (from pyautogui) (0.1.28)
Requirement already satisfied: python3-Xlib in /home/s1yn/.local/lib/python3.11/site-packages (from pyautogui) (0.15)
Requirement already satisfied: pyrect in /home/s1yn/.local/lib/python3.11/site-packages (from pygetwindow>=0.0.5->pyautogui) (0.2.0)
Requirement already satisfied: pyperclip in /usr/lib/python3/dist-packages (from mouseinfo->pyautogui) (1.8.2)
                                                                                                                                                                      
┌──(s1yn㉿sec)-[~/AutoSnapBot]
└─$ sudo import pyautogui 
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/421.
                                                                                                                                                                      
┌──(s1yn㉿sec)-[~/AutoSnapBot]
└─$ 
                                                                                                                                                                      
┌──(s1yn㉿sec)-[~/AutoSnapBot]
└─$ import pyautogui

import-im6.q16: unable to open image `pyautogui': Permission denied @ error/blob.c/OpenBlob/2924.
import-im6.q16: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/421.

**Comment by Jirgap** [comment]
As you are using **linux**, please add to the top of each file:
```
#!/usr/bin/env python3
```
You also should **not** run as a superuser (sudo command) as the script should not be run with root privileges and that is most likley why are you are having the security policy issue

To run the code ensure you are using python3 not python2 as this is coded in python3

Please let me know if that fixed all the issues :))

**Comment by Jirgap** [comment]
No follow up so will close
